### ISSUE TITLE
Upgrade jQuery

### ISSUE THREAD

**Issue by VirtualRichard** [neurospeech/atoms.js#110]
Hello, Atoms NuGet brings in jQuery 1.11.1, which is quite old. NuGet cannot upgrade this jQuery as there isn't a compatible version of Atoms it can find.

I'm evaluating JavaScript frameworks, Atoms looks good but I think the jQuery is too old.

**Comment by neurospeech** [comment]
We have removed that restriction.

We have been supporting IE < v9, so we had fixed jQuery to version 1.11.1, .Now you can upgrade your jQuery. We are also planning non jQuery Atoms.js very soon, as we are only using $.css and other small utility methods. jQuery is very slow in navigating dom, we have our own faster version of dom navigation.
